@RiverBooks.Api_HostAdress = https://localhost:7290

### Get All Books

GET {{RiverBooks.Api_HostAdress}}/books
Accept: application/json

### Get Book By Id

@BookId = A89F6CD7-4693-457B-9009-02205DBBFE45
GET {{RiverBooks.Api_HostAdress}}/books/{{BookId}}
Accept: application/json

### Create new Book

POST {{RiverBooks.Api_HostAdress}}/books/
Accept: application/json
Content-Type: application/json

{
    "id": "988B0272-5FAE-428E-A87C-08E5B7B9BD8C",
    "title": "Modular Monoliths - Getting Started",
    "author": "Steve Smith",
    "price": 29.99
}

### Test Get new Book by Id from POST header location

GET {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c
Accept: application/json

### Update Book 

POST {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c/price-history
Accept: application/json
Content-Type: application/json

{
    "newPrice": 9.99
}

### Delete Book by Id

DELETE {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c
Accept: application/json

### Update Book with invalid new price

POST {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c/price-history
Accept: application/json
Content-Type: application/json

{
    "newPrice": -9.99
}

### Create new user

POST {{RiverBooks.Api_HostAdress}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "kk@test.com",
    "password": "Pass@word1"
}

### Login new user

POST {{RiverBooks.Api_HostAdress}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "kk@test.com",
    "password": "Pass@word1"
}

### Add Item to cart

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJra0B0ZXN0LmNvbSIsImlhdCI6MTcxMDUyMjE3OSwiZXhwIjoxNzEwNTI1Nzc5LCJuYmYiOjE3MTA1MjIxNzl9.xCQ3dE_WSuyPQjWnW-LjelflyLHuJh4eW6t4AKBSS2Y

POST {{RiverBooks.Api_HostAdress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "A89F6CD7-4693-457B-9009-02205DBBFE45",
    "quantity": 1
}

### List items in cart

GET {{RiverBooks.Api_HostAdress}}/cart
Accept: application/json
Authorization: Bearer {{token}}