@RiverBooks.Api_HostAdress = https://localhost:7290

### Get All Books

GET {{RiverBooks.Api_HostAdress}}/books
Accept: application/json

### Get Book By Id

@BookId = A89F6CD7-4693-457B-9009-02205DBBFE45
GET {{RiverBooks.Api_HostAdress}}/books/{{BookId}}
Accept: application/json

### Create new Book

POST {{RiverBooks.Api_HostAdress}}/books/
Accept: application/json
Content-Type: application/json

{
    "id": "988B0272-5FAE-428E-A87C-08E5B7B9BD8C",
    "title": "Modular Monoliths - Getting Started",
    "author": "Steve Smith",
    "price": 29.99
}

### Test Get new Book by Id from POST header location

GET {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c
Accept: application/json

### Update Book 

POST {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c/price-history
Accept: application/json
Content-Type: application/json

{
    "newPrice": 9.99
}

### Delete Book by Id

DELETE {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c
Accept: application/json

### Update Book with invalid new price

POST {{RiverBooks.Api_HostAdress}}/books/988b0272-5fae-428e-a87c-08e5b7b9bd8c/price-history
Accept: application/json
Content-Type: application/json

{
    "newPrice": -9.99
}

### Create new user

POST {{RiverBooks.Api_HostAdress}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "kk3@test.com",
    "password": "Pass@word1"
}

### Create new invalid user

POST {{RiverBooks.Api_HostAdress}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "kk2@test.com",
    "password": ""
}

### Login new user

POST {{RiverBooks.Api_HostAdress}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "kk@test.com",
    "password": "Pass@word1"
}

### Add Item to cart

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJra0B0ZXN0LmNvbSIsImlhdCI6MTcxMDY5MjU5OCwiZXhwIjoxNzEwNjk2MTk4LCJuYmYiOjE3MTA2OTI1OTh9.B3je_S-D5ynoRd7RhAEUlLnsXTjG59q41HGTS2MhN3E

POST {{RiverBooks.Api_HostAdress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "A89F6CD7-4693-457B-9009-02205DBBFE45",
    "quantity": 0
}

### Add Item with invalid quantity to cart

POST {{RiverBooks.Api_HostAdress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "A89F6CD7-4693-457B-9009-02205DBBFE45",
    "quantity": 0
}

### List items in cart

GET {{RiverBooks.Api_HostAdress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

### List all orders

GET {{RiverBooks.Api_HostAdress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

### Checkout Cart

POST {{RiverBooks.Api_HostAdress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "shippingAddressId": "8e5f4d20-fb73-4725-844f-aab71f5e4355",
    "billingAddressId": "8e5f4d20-fb73-4725-844f-aab71f5e4355"
}

### Add Address to User

POST {{RiverBooks.Api_HostAdress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "street1": "2 Main St.",
    "street2": "Number 722",
    "city": "Anytown",
    "state": "OH",
    "postalCode": "12345-6789",
    "country": "USA"
}

### List Addresses

GET {{RiverBooks.Api_HostAdress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

### Flush Redis cache (Testing only)

POST {{RiverBooks.Api_HostAdress}}/flushcache
Accept: application/json
Content-Type: application/json

{
}

###